livre_ajout:
    path: '/livres/ajout'
    controller: App\Controller\LivreController::ajout
livre_modif:
    path: '/livres/modifier/{id}'
    controller: 'App\Controller\LivreController::modifierLivre'
auteurs:
    path: /auteurs
    controller: App\Controller\AuteurController::index
